slides.html: slides.org
	docker run --rm -v `pwd`:/ox nilcons/ox

reveal-dl:
	wget -O revealjs/css/reveal.css http://cdn.jsdelivr.net/reveal.js/2.5.0/css/reveal.min.css
	wget -O revealjs/css/theme/simple.css http://cdn.jsdelivr.net/reveal.js/2.5.0/css/theme/simple.css
	wget -O revealjs/lib/js/head.min.js  http://cdn.jsdelivr.net/reveal.js/2.5.0/lib/js/head.min.js
	wget -O revealjs/js/reveal.js  http://cdn.jsdelivr.net/reveal.js/2.5.0/js/reveal.min.js
